version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: platform_dev

